version: '3.8'
services:
  test:
    build:
      context: .
      target: test
      dockerfile: Dockerfile
  deploy:
    build:
      context: .
      target: deploy
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 80
    ports:
      - ${SYL_PORT_DEPLOY}:80    
  dev:
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
      args:
        GID: ${MY_GID}
        UID: ${MY_UID}
    volumes:
      - .:/code/app
    environment:
      - PYTHONPATH=/code/app/src
      - MYPYPATH=/code/app/src
    tty: true 
  